### ISSUE TITLE
Document/list points of discussion and advice from professor

### ISSUE THREAD

**Issue by thegreyd** [SE17GroupH/SE17_TeamH_Ideas#15]
Either we can list them here on in the projects todo list.

**Comment by DevArenaCN** [comment]
We can do it here in the issue list. I'm at work now and don't have my laptop with me, I'll have to list them later.

**Comment by thegreyd** [comment]
Topics included 
- Biometric authentication
    - heartbeat
    - iris
    - way a person walks or performs a physical action
    - voice
    - face
    - typing
- Authentication using user preference
    - sort these images based on how much you like them
    - succession of activities like these might constitute a password
- Survey evaluation criteria
    - time it takes user to sign up for the accounts
    - time it takes user to login to the accounts
    - order of login and signup maybe random.

**Comment by DevArenaCN** [comment]
For iris scanner, I couldn't find any library other than OpenCV, I think you can do an Android app using that library, for iOS I think the only way would be start from scratch, which is not ideal. As for heartbeat, I haven't search for any papers yet but I do know that FitBit have an API that can grab that data. Not sure how we're going to use it, need some input on this.

**Comment by DevArenaCN** [comment]
Links from yersterday's meeting:
https://www.researchgate.net/profile/Nisha_Chabbra2/publication/302953237_Low_Quality_Iris_Detection_in_Smart_Phone_A_Survey/links/5734259808ae9f741b261ed7.pdf

https://scholar.google.com/scholar?as_ylo=2013&q=mobile+phone+biometrics&hl=en&as_sdt=0,34

gait, voice
iris

**Comment by DevArenaCN** [comment]
I have added some papers on gaits recognition in the papers folder, I'll do some search on voice later tonight.

**Comment by DevArenaCN** [comment]
For Voice Recognition I've found a library called [VoiceVault](http://voicevault.com/support/voice-biometric-tutorials-and-howtos/) and I think it's on iOS platform. It offers a 45 days trail which I think would be plenty for us to implement  

For Android I found one called [recognito](https://github.com/amaurycrickx/recognito), which is open-sourced. Another one is called [MARF（Modular Audio Recognition Framework)](http://marf.sourceforge.net/). Problem with these two, they both are out-dated (First one from 2012, second have no update since 2006), not sure if they're compatible with the current SDK or not.

There's also an Java library called [Sphinx](http://cmusphinx.sourceforge.net/wiki/tutorialsphinx4/).

**Comment by KaustubhG** [comment]
Here is something I found on voice too:

https://siv.voiceprintportal.com/
Though this is a paid service, it is pretty cheap : $25/month for 1000 API calls
The API is a bunch of REST calls.
Since its REST calls, I guess we could add it to mobile apps too.

**Comment by DevArenaCN** [comment]
Oh, I didn't find that one, but it looks promising. For heartbeat recognition, I don't think we'll be able to pull it off since the research paper is very vague on how they did it, so I suspect they didn't get a specific model on how to convert heartbeat into a way to use as password that is accurate enough to separate each individual.

**Comment by KaustubhG** [comment]
Here is a Microsoft offering I found on voice! :-)

https://www.microsoft.com/cognitive-services/en-us/speaker-recognition-api
Seems to be the best by far.
10K calls per month free!
Also supported on android and iOS.

**Comment by DevArenaCN** [comment]
By the way, I'm documenting everything we've found in [here](https://github.com/SE17GroupH/SE17_TeamH_Ideas/blob/master/Implementations/readme.MD)

**Comment by thegreyd** [comment]
Closing, since we have our points.
